services:

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - my-network
  
  web:
    build: .
    command: 
       sh -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - elasticsearch
    networks:
      - my-network
      
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
    networks:
      - my-network

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/code 
    depends_on:
      - web
      - rabbitmq
    networks:
      - my-network
    
  flower:
    image: mher/flower:latest
    command:  ['celery', '--broker=amqp://guest:guest@rabbitmq:5672//', 'flower', '--port=5555']
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
    networks:
      - my-network
        
  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge